#!/bin/bash

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$UID}"

if [ ! -d "$XDG_STATE_HOME/bash" ]; then
	mkdir -p "$XDG_STATE_HOME/bash"
fi
export HISTFILE="$XDG_STATE_HOME/bash/history"
export HISTSIZE=10000
export HISTCONTROL="ignoreboth"

if command -v nvim &> /dev/null; then
	export EDITOR="/usr/bin/nvim"
	export MANPAGER="nvim +Man!"
fi

if command -v clang &> /dev/null; then
	export CC="/usr/bin/clang"
fi
if command -v clang++ &> /dev/null; then
	export CXX="/usr/bin/clang++"
fi

if command -v npm &> /dev/null; then
	export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
	export NPM_CONFIG_INIT_MODULE="$XDG_CONFIG_HOME/npm/npm-init.js"
	export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
	export NPM_CONFIG_PREFIX="$XDG_DATA_HOME/npm"
	export PATH="$PATH:$XDG_DATA_HOME/npm/bin"
fi

if command -v rustup &> /dev/null; then
	export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
fi
if command -v cargo &> /dev/null; then
	export CARGO_HOME="$XDG_DATA_HOME/cargo"
fi

if [ -d "/usr/lib/jvm/default/bin" ]; then
	export PATH="$PATH:/usr/lib/jvm/default/bin"
fi

if command -v xauth &> /dev/null; then
	export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
fi
if command -v iceauth &> /dev/null; then
	export ICEAUTHORITY="$XDG_CACHE_HOME/ICEauthority"
fi

if command -v gpg &> /dev/null; then
	export GNUPGHOME="$XDG_DATA_HOME/gnupg"
fi

if [ -d "$HOME/.local/bin" ]; then
    PATH="$HOME/.local/bin:$PATH"
fi
